version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "80:80"
    environment:
      - DB_HOST=mysql
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    volumes:
      - ./var/www/html/laravel_app:/var/www/html
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - /var/www/html/mysql-data:/var/lib/mysql
