# Use the official MySQL image as the base image
FROM mysql:5.7

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mywebsite
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword


#Copy the initialization script to Docker entrypoint
COPY init_db.sql /docker-entrypoint-initdb.d/

# Expose port 3306 for MySQL
EXPOSE 3306
